import java.util.ArrayList;
public class populatepaper {
    public static void pop(ArrayList<paper> paperinventory){
        paper SmallCups = new paper();
        paper MediumCups = new paper();
        paper LargeCups = new paper();
        paper SmallLids = new paper();
        paper MediumLids = new paper();
        paper LargeLids = new paper();
        paper SmallBoats = new paper();
        paper LargeBoats = new paper();
        paper Spoons = new paper();
        paper Napkins = new paper();

        paperinventory.add(SmallCups);
            SmallCups.setName("Small Cups");
            SmallCups.setDetails("8oz");
            SmallCups.setVendor("South Jersey Paper");
            SmallCups.setInStock(true);
            SmallCups.setStandardAmount(4);
            SmallCups.setPrice(80);
        paperinventory.add(MediumCups);
            MediumCups.setName("Medium Cups");
            MediumCups.setDetails("12oz");
            MediumCups.setVendor("South Jersey Paper");
            MediumCups.setInStock(true);
            MediumCups.setStandardAmount(4);
            MediumCups.setPrice(80);
        paperinventory.add(LargeCups);
            LargeCups.setName("Large Cups");
            LargeCups.setDetails("16oz");
            LargeCups.setVendor("South Jersey Paper");
            LargeCups.setInStock(true);
            LargeCups.setStandardAmount(4);
            LargeCups.setPrice(80);
        paperinventory.add(SmallLids);
            SmallLids.setName("Small Cups");
            SmallLids.setVendor("South Jersey Paper");
            SmallLids.setInStock(true);
            SmallLids.setStandardAmount(4);
            SmallLids.setPrice(50);
        paperinventory.add(MediumLids);
            MediumLids.setName("Medium Lids");
            MediumLids.setVendor("South Jersey Paper");
            MediumLids.setInStock(true);
            MediumLids.setStandardAmount(4);
            MediumLids.setPrice(50);
        paperinventory.add(LargeLids);
            LargeLids.setName("Large Lids");
            LargeLids.setVendor("South Jersey Paper");
            LargeLids.setInStock(true);
            LargeLids.setStandardAmount(4);
            LargeLids.setPrice(50);
        paperinventory.add(SmallBoats);
            SmallBoats.setName("Small Boats");
            SmallBoats.setDetails("16oz");
            SmallBoats.setVendor("South Jersey Paper");
            SmallBoats.setInStock(true);
            SmallBoats.setStandardAmount(3);
            SmallBoats.setPrice(80);
        paperinventory.add(LargeBoats);
            LargeBoats.setName("Large Boats");
            LargeBoats.setDetails("16oz");
            LargeBoats.setVendor("South Jersey Paper");
            LargeBoats.setInStock(true);
            LargeBoats.setStandardAmount(3);
            LargeBoats.setPrice(80);
        paperinventory.add(Spoons);
            Spoons.setName("Spoons");
            Spoons.setVendor("South Jersey Paper");
            Spoons.setInStock(true);
            Spoons.setStandardAmount(3);
            Spoons.setPrice(40);
        paperinventory.add(Napkins);
            Napkins.setName("Napkins");
            Napkins.setVendor("South Jersey Paper");
            Napkins.setInStock(true);
            Napkins.setStandardAmount(5);
            Napkins.setPrice(40);
    }
}
