import java.util.ArrayList;
public class populatetopping {
    public static void pop(ArrayList<topping> toppinginventory){
        topping RainbowSprinkles = new topping();
        topping ChocolateSprinkles = new topping();
        topping HotFudge = new topping();
        topping Caramel = new topping();
        topping PeanutButter = new topping();
        topping Marshmallow = new topping();
        topping ChocolateSyrup = new topping();
        topping VanillaSyrup = new topping();
        topping CherrySyrup = new topping();
        topping CoffeeSyrup = new topping();
        topping Strawberries = new topping();
        topping Pineapple = new topping();
        topping CookieDoughPieces = new topping();
        topping MMs = new topping();
        topping ReecesPieces = new topping();
        topping GummyBears = new topping();
        topping Oreos = new topping();
        topping Heath = new topping();
        topping ChocChips = new topping();
        topping Cherries = new topping();
        topping WhippedCream = new topping();
        topping PBCups = new topping();
        topping SugarCone = new topping();
        topping WaferCone = new topping();
        topping WaffleCone = new topping();
        topping Malt = new topping();

        toppinginventory.add(RainbowSprinkles);
            RainbowSprinkles.setName("Rainbow Sprinkles");
            RainbowSprinkles.setTemp("Room");
            RainbowSprinkles.setVendor("Panza"); //ADD IN PANZA
            RainbowSprinkles.setInStock(true);
            RainbowSprinkles.setStandardAmount(4);
            RainbowSprinkles.setPrice(60/4);
            RainbowSprinkles.setPeanut(false);
            RainbowSprinkles.setMilk(false);
            RainbowSprinkles.setTreeNuts(false);
            RainbowSprinkles.setWheat(true);
            RainbowSprinkles.setSoy(true);
        toppinginventory.add(ChocolateSprinkles);
            ChocolateSprinkles.setName("Chocolate Sprinkles");
            ChocolateSprinkles.setTemp("Room");
            ChocolateSprinkles.setVendor("Panza");
            ChocolateSprinkles.setInStock(true);
            ChocolateSprinkles.setStandardAmount(4);
            ChocolateSprinkles.setPrice(60/4);
            ChocolateSprinkles.setPeanut(false);
            ChocolateSprinkles.setMilk(false);
            ChocolateSprinkles.setTreeNuts(false);
            ChocolateSprinkles.setWheat(true);
            ChocolateSprinkles.setSoy(true);
        toppinginventory.add(HotFudge);
            HotFudge.setName("Hot Fudge");
            HotFudge.setTemp("Hot");
            HotFudge.setVendor("Panza");
            HotFudge.setInStock(true);
            HotFudge.setStandardAmount(4);
            HotFudge.setPrice(18);
            HotFudge.setPeanut(false);
            HotFudge.setMilk(true);
            HotFudge.setTreeNuts(false);
            HotFudge.setWheat(false);
            HotFudge.setSoy(false);
        toppinginventory.add(Caramel);
            Caramel.setName("Caramel");
            Caramel.setTemp("Room");
            Caramel.setVendor("Panza");
            Caramel.setInStock(true);
            Caramel.setStandardAmount(2);
            Caramel.setPrice(22);
            Caramel.setPeanut(false);
            Caramel.setMilk(false);
            Caramel.setTreeNuts(false);
            Caramel.setWheat(false);
            Caramel.setSoy(false);
        toppinginventory.add(PeanutButter);
            PeanutButter.setName("Peanut Butter");
            PeanutButter.setTemp("Room");
            PeanutButter.setVendor("Panza");
            PeanutButter.setInStock(true);
            PeanutButter.setStandardAmount(2);
            PeanutButter.setPrice(16);
            PeanutButter.setPeanut(true);
            PeanutButter.setMilk(false);
            PeanutButter.setTreeNuts(false);
            PeanutButter.setWheat(false);
            PeanutButter.setSoy(false);
        toppinginventory.add(Marshmallow);
            Marshmallow.setName("Marshmallow");
            Marshmallow.setTemp("Room");
            Marshmallow.setVendor("Panza");
            Marshmallow.setInStock(true);
            Marshmallow.setStandardAmount(2);
            Marshmallow.setPrice(12);
            Marshmallow.setPeanut(false);
            Marshmallow.setMilk(false);
            Marshmallow.setTreeNuts(false);
            Marshmallow.setWheat(false);
            Marshmallow.setSoy(true);
        toppinginventory.add(ChocolateSyrup);
            ChocolateSyrup.setName("Chocolate Syrup");
            ChocolateSyrup.setTemp("Room");
            ChocolateSyrup.setVendor("Panza");
            ChocolateSyrup.setInStock(true);
            ChocolateSyrup.setStandardAmount(3);
            ChocolateSyrup.setPrice(60/4);
            ChocolateSyrup.setPeanut(false);
            ChocolateSyrup.setMilk(true);
            ChocolateSyrup.setTreeNuts(false);
            ChocolateSyrup.setWheat(false);
            ChocolateSyrup.setSoy(false);
        toppinginventory.add(VanillaSyrup);
            VanillaSyrup.setName("Vanilla Syrup");
            VanillaSyrup.setTemp("Room");
            VanillaSyrup.setVendor("Panza");
            VanillaSyrup.setInStock(true);
            VanillaSyrup.setStandardAmount(1);
            VanillaSyrup.setPrice(52/4);
            VanillaSyrup.setPeanut(false);
            VanillaSyrup.setMilk(false);
            VanillaSyrup.setTreeNuts(false);
            VanillaSyrup.setWheat(false);
            VanillaSyrup.setSoy(false);
        toppinginventory.add(CherrySyrup);
            CherrySyrup.setName("Cherry Syrup");
            CherrySyrup.setTemp("Room");
            CherrySyrup.setVendor("Panza");
            CherrySyrup.setInStock(true);
            CherrySyrup.setStandardAmount(1);
            CherrySyrup.setPrice(20);
            CherrySyrup.setPeanut(false);
            CherrySyrup.setMilk(false);
            CherrySyrup.setTreeNuts(false);
            CherrySyrup.setWheat(false);
            CherrySyrup.setSoy(true);
        toppinginventory.add(CoffeeSyrup);
            CoffeeSyrup.setName("Coffee Syrup");
            CoffeeSyrup.setTemp("Room");
            CoffeeSyrup.setVendor("Panza");
            CoffeeSyrup.setInStock(true);
            CoffeeSyrup.setStandardAmount(1);
            CoffeeSyrup.setPrice(20);
            CoffeeSyrup.setPeanut(false);
            CoffeeSyrup.setMilk(false);
            CoffeeSyrup.setTreeNuts(false);
            CoffeeSyrup.setWheat(false);
            CoffeeSyrup.setSoy(false);
        toppinginventory.add(Strawberries);
            Strawberries.setName("Strawberries");
            Strawberries.setTemp("Room");
            Strawberries.setVendor("Panza");
            Strawberries.setInStock(true);
            Strawberries.setStandardAmount(1);
            Strawberries.setPrice(15);
            Strawberries.setPeanut(false);
            Strawberries.setMilk(false);
            Strawberries.setTreeNuts(false);
            Strawberries.setWheat(false);
            Strawberries.setSoy(false);
        toppinginventory.add(Pineapple);
            Pineapple.setName("Pineapple");
            Pineapple.setTemp("Room");
            Pineapple.setVendor("Panza");
            Pineapple.setInStock(true);
            Pineapple.setStandardAmount(1);
            Pineapple.setPrice(66/6);
            Pineapple.setPeanut(false);
            Pineapple.setMilk(false);
            Pineapple.setTreeNuts(false);
            Pineapple.setWheat(false);
            Pineapple.setSoy(false);
        toppinginventory.add(CookieDoughPieces);
            CookieDoughPieces.setName("Cookie Dough Pieces");
            CookieDoughPieces.setTemp("Fridge");
            CookieDoughPieces.setVendor("Panza");
            CookieDoughPieces.setInStock(true);
            CookieDoughPieces.setStandardAmount(2);
            CookieDoughPieces.setPrice(35);
            CookieDoughPieces.setPeanut(false);
            CookieDoughPieces.setMilk(false);
            CookieDoughPieces.setTreeNuts(false);
            CookieDoughPieces.setWheat(true);
            CookieDoughPieces.setSoy(true);
        toppinginventory.add(MMs);
            MMs.setName("M&Ms");
            MMs.setTemp("Room");
            MMs.setVendor("Panza");
            MMs.setInStock(true);
            MMs.setStandardAmount(2);
            MMs.setPrice(32);
            MMs.setPeanut(false);
            MMs.setMilk(true);
            MMs.setTreeNuts(false);
            MMs.setWheat(false);
            MMs.setSoy(false);
        toppinginventory.add(ReecesPieces);
            ReecesPieces.setName("Reece's Pieces");
            ReecesPieces.setTemp("Room");
            ReecesPieces.setVendor("Panza");
            ReecesPieces.setInStock(true);
            ReecesPieces.setStandardAmount(2);
            ReecesPieces.setPrice(30);
            ReecesPieces.setPeanut(true);
            ReecesPieces.setMilk(true);
            ReecesPieces.setTreeNuts(false);
            ReecesPieces.setWheat(false);
            ReecesPieces.setSoy(false);
        toppinginventory.add(GummyBears);
            GummyBears.setName("Gummy Bears");
            GummyBears.setTemp("Room");
            GummyBears.setVendor("Panza");
            GummyBears.setInStock(true);
            GummyBears.setStandardAmount(1);
            GummyBears.setPrice(72/4);
            GummyBears.setPeanut(false);
            GummyBears.setMilk(false);
            GummyBears.setTreeNuts(false);
            GummyBears.setWheat(false);
            GummyBears.setSoy(true);
        toppinginventory.add(Oreos);
            Oreos.setName("Oreos");
            Oreos.setTemp("Room");
            Oreos.setVendor("Panza");
            Oreos.setInStock(true);
            Oreos.setStandardAmount(2);
            Oreos.setPrice(56/4);
            Oreos.setPeanut(false);
            Oreos.setMilk(false);
            Oreos.setTreeNuts(false);
            Oreos.setWheat(true);
            Oreos.setSoy(true);
        toppinginventory.add(Heath);
            Heath.setName("Heath");
            Heath.setTemp("Fridge");
            Heath.setVendor("Panza");
            Heath.setInStock(true);
            Heath.setStandardAmount(1);
            Heath.setPrice(26);
            Heath.setPeanut(false);
            Heath.setMilk(true);
            Heath.setTreeNuts(false);
            Heath.setWheat(true);
            Heath.setSoy(true);
        toppinginventory.add(ChocChips);
            ChocChips.setName("Chocolate Chips");
            ChocChips.setTemp("Fridge");
            ChocChips.setVendor("Panza");
            ChocChips.setInStock(true);
            ChocChips.setStandardAmount(1);
            ChocChips.setPrice(80);
            ChocChips.setPeanut(false);
            ChocChips.setMilk(true);
            ChocChips.setTreeNuts(false);
            ChocChips.setWheat(false);
            ChocChips.setSoy(false);
        toppinginventory.add(Cherries);
            Cherries.setName("Cherries");
            Cherries.setTemp("Fridge");
            Cherries.setVendor("Panza");
            Cherries.setInStock(true);
            Cherries.setStandardAmount(2);
            Cherries.setPrice(68/4);
            Cherries.setPeanut(false);
            Cherries.setMilk(false);
            Cherries.setTreeNuts(false);
            Cherries.setWheat(false);
            Cherries.setSoy(false);
        toppinginventory.add(WhippedCream);
            WhippedCream.setName("Whipped Cream");
            WhippedCream.setTemp("Fridge");
            WhippedCream.setVendor("Panza");
            WhippedCream.setInStock(true);
            WhippedCream.setStandardAmount(6);
            WhippedCream.setPrice(55);
            WhippedCream.setPeanut(false);
            WhippedCream.setMilk(true);
            WhippedCream.setTreeNuts(false);
            WhippedCream.setWheat(false);
            WhippedCream.setSoy(false);
        toppinginventory.add(PBCups);
            PBCups.setName("Peanut Butter Cups");
            PBCups.setTemp("Fridge");
            PBCups.setVendor("Panza");
            PBCups.setInStock(true);
            PBCups.setStandardAmount(2);
            PBCups.setPrice(28);
            PBCups.setPeanut(true);
            PBCups.setMilk(true);
            PBCups.setTreeNuts(false);
            PBCups.setWheat(false);
            PBCups.setSoy(false);
        toppinginventory.add(SugarCone);
            SugarCone.setName("Sugar Cone");
            SugarCone.setTemp("Room");
            SugarCone.setVendor("South Jersey Paper");
            SugarCone.setInStock(true);
            SugarCone.setStandardAmount(2);
            SugarCone.setPrice(82);
            SugarCone.setPeanut(false);
            SugarCone.setMilk(true);
            SugarCone.setTreeNuts(false);
            SugarCone.setWheat(true);
            SugarCone.setSoy(false);
        toppinginventory.add(WaferCone);
            WaferCone.setName("Wafer Cone");
            WaferCone.setTemp("Room");
            WaferCone.setVendor("South Jersey Paper");
            WaferCone.setInStock(true);
            WaferCone.setStandardAmount(3);
            WaferCone.setPrice(72);
            WaferCone.setPeanut(false);
            WaferCone.setMilk(true);
            WaferCone.setTreeNuts(false);
            WaferCone.setWheat(true);
            WaferCone.setSoy(false);
        toppinginventory.add(WaffleCone);
            WaffleCone.setName("Waffle Cone");
            WaffleCone.setTemp("Room");
            WaffleCone.setVendor("South Jersey Paper");
            WaffleCone.setInStock(true);
            WaffleCone.setStandardAmount(2);
            WaffleCone.setPrice(56);
            WaffleCone.setPeanut(false);
            WaffleCone.setMilk(true);
            WaffleCone.setTreeNuts(false);
            WaffleCone.setWheat(true);
            WaffleCone.setSoy(false);
        toppinginventory.add(Malt);
            Malt.setName("Malt Powder");
            Malt.setTemp("Room");
            Malt.setVendor("Panza");
            Malt.setInStock(true);
            Malt.setStandardAmount(1);
            Malt.setPrice(15);
            Malt.setPeanut(false);
            Malt.setMilk(false);
            Malt.setTreeNuts(false);
            Malt.setWheat(false);
            Malt.setSoy(false);
    }
}
